apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../base]
images:
  - { name: ghcr.io/sm2774us/pnc-risk-console-bff, newTag: '1.0.0' }
  - { name: ghcr.io/sm2774us/pnc-risk-console-web, newTag: '1.0.0' }
patches:
  - target: { kind: Deployment, name: bff }
    patch: |-
      - { op: replace, path: /spec/replicas, value: 3 }
