import type { Lob, Peril, Rating, ReturnPeriod, Zone } from './types';

export const LOBS: readonly Lob[] = [
  'Commercial Property',
  'Homeowners',
  'Marine Cargo',
  'General Liability',
  'Cyber',
  'Aviation',
  'Auto Fleet',
];
export const PERILS: readonly Peril[] = ['Windstorm', 'Flood', 'Earthquake', 'Wildfire', 'Fire', 'Liability', 'Cyber Event'];
export const RATINGS: readonly Rating[] = ['A', 'B', 'C', 'D', 'E'];
export const RETURN_PERIODS: readonly ReturnPeriod[] = [10, 50, 100, 250, 500];

/** Which perils each line of business is exposed to (drives synthetic data and validation). */
export const LOB_PERILS: Record<Lob, readonly Peril[]> = {
  'Commercial Property': ['Windstorm', 'Flood', 'Earthquake', 'Wildfire', 'Fire'],
  Homeowners: ['Windstorm', 'Flood', 'Wildfire', 'Fire'],
  'Marine Cargo': ['Windstorm', 'Flood', 'Fire'],
  'General Liability': ['Liability'],
  Cyber: ['Cyber Event'],
  Aviation: ['Liability', 'Fire'],
  'Auto Fleet': ['Liability', 'Flood'],
};

/** Base mean damage ratio of TIV per peril (illustrative, not calibrated to a vendor cat model). */
export const PERIL_BASE_RATE: Record<Peril, number> = {
  Windstorm: 0.0042,
  Flood: 0.0031,
  Earthquake: 0.0026,
  Wildfire: 0.0022,
  Fire: 0.0018,
  Liability: 0.0012,
  'Cyber Event': 0.0035,
};

/** Return-period damage-ratio multipliers over the base rate (heavier tail for cat perils). */
export const RP_MULTIPLIER: Record<ReturnPeriod, number> = { 10: 3, 50: 9, 100: 14, 250: 21, 500: 28 };
/** Cat perils accumulate per zone; non-cat perils have a flatter tail. */
export const TAIL_FACTOR: Record<Peril, number> = {
  Windstorm: 1.3,
  Flood: 1.2,
  Earthquake: 1.5,
  Wildfire: 1.15,
  Fire: 0.7,
  Liability: 0.5,
  'Cyber Event': 1.1,
};

export const BASE_APPETITE_TIV = 4_000_000_000;
export const WATCH_THRESHOLD = 0.8;
export const BREACH_THRESHOLD = 1;

const H = (x: Partial<Record<Peril, number>>) => x;
export const ZONES: readonly Zone[] = [
  {
    code: 'US-FL',
    name: 'Florida',
    country: 'US',
    tile: { col: 8, row: 5 },
    weight: 9,
    capacity: 1.0,
    hazard: H({ Windstorm: 2.4, Flood: 2.0, Fire: 1, Liability: 1, 'Cyber Event': 1 }),
  },
  {
    code: 'US-TX',
    name: 'Texas',
    country: 'US',
    tile: { col: 5, row: 4 },
    weight: 10,
    capacity: 1.4,
    hazard: H({ Windstorm: 1.7, Flood: 1.5, Fire: 1, Liability: 1, 'Cyber Event': 1 }),
  },
  {
    code: 'US-LA',
    name: 'Louisiana',
    country: 'US',
    tile: { col: 6, row: 5 },
    weight: 4,
    capacity: 0.7,
    hazard: H({ Windstorm: 2.2, Flood: 2.3, Fire: 1, Liability: 1 }),
  },
  {
    code: 'US-CA',
    name: 'California',
    country: 'US',
    tile: { col: 1, row: 3 },
    weight: 11,
    capacity: 1.5,
    hazard: H({ Earthquake: 2.6, Wildfire: 2.5, Fire: 1.1, Liability: 1, 'Cyber Event': 1.1 }),
  },
  {
    code: 'US-WA',
    name: 'Washington',
    country: 'US',
    tile: { col: 1, row: 1 },
    weight: 4,
    capacity: 0.8,
    hazard: H({ Earthquake: 2.0, Wildfire: 1.2, Flood: 1, Liability: 1, 'Cyber Event': 1 }),
  },
  {
    code: 'US-NY',
    name: 'New York',
    country: 'US',
    tile: { col: 10, row: 2 },
    weight: 10,
    capacity: 1.6,
    hazard: H({ Windstorm: 1.3, Flood: 1.2, Fire: 1, Liability: 1.2, 'Cyber Event': 1.4 }),
  },
  {
    code: 'US-IL',
    name: 'Illinois',
    country: 'US',
    tile: { col: 7, row: 2 },
    weight: 6,
    capacity: 1.2,
    hazard: H({ Windstorm: 1.1, Flood: 1, Fire: 1, Liability: 1, 'Cyber Event': 1.1 }),
  },
  {
    code: 'US-NC',
    name: 'North Carolina',
    country: 'US',
    tile: { col: 9, row: 4 },
    weight: 4,
    capacity: 0.8,
    hazard: H({ Windstorm: 1.8, Flood: 1.6, Fire: 1, Liability: 1 }),
  },
  {
    code: 'CA-ON',
    name: 'Ontario',
    country: 'CA',
    tile: { col: 9, row: 1 },
    weight: 4,
    capacity: 1.0,
    hazard: H({ Windstorm: 0.8, Flood: 0.9, Fire: 1, Liability: 1, 'Cyber Event': 1 }),
  },
  {
    code: 'CA-BC',
    name: 'British Columbia',
    country: 'CA',
    tile: { col: 0, row: 1 },
    weight: 3,
    capacity: 0.8,
    hazard: H({ Earthquake: 1.9, Wildfire: 1.7, Flood: 1, Fire: 1, Liability: 1 }),
  },
  {
    code: 'MX-CMX',
    name: 'Mexico City',
    country: 'MX',
    tile: { col: 4, row: 6 },
    weight: 3,
    capacity: 0.6,
    hazard: H({ Earthquake: 2.4, Flood: 1.3, Fire: 1, Liability: 1 }),
  },
  {
    code: 'BR-SP',
    name: 'São Paulo',
    country: 'BR',
    tile: { col: 6, row: 8 },
    weight: 3,
    capacity: 0.6,
    hazard: H({ Flood: 1.5, Fire: 1, Liability: 1, 'Cyber Event': 1 }),
  },
  {
    code: 'GB-LON',
    name: 'London',
    country: 'GB',
    tile: { col: 13, row: 1 },
    weight: 9,
    capacity: 1.6,
    hazard: H({ Windstorm: 1.0, Flood: 1.1, Fire: 1, Liability: 1.2, 'Cyber Event': 1.5 }),
  },
  {
    code: 'NL-ZH',
    name: 'South Holland',
    country: 'NL',
    tile: { col: 14, row: 1 },
    weight: 3,
    capacity: 0.8,
    hazard: H({ Windstorm: 1.2, Flood: 1.8, Fire: 1, Liability: 1 }),
  },
  {
    code: 'DE-BY',
    name: 'Bavaria',
    country: 'DE',
    tile: { col: 14, row: 2 },
    weight: 5,
    capacity: 1.0,
    hazard: H({ Windstorm: 1.3, Flood: 1.3, Fire: 1, Liability: 1, 'Cyber Event': 1.1 }),
  },
  {
    code: 'FR-IDF',
    name: 'Île-de-France',
    country: 'FR',
    tile: { col: 13, row: 2 },
    weight: 4,
    capacity: 0.9,
    hazard: H({ Windstorm: 1.1, Flood: 1.4, Fire: 1, Liability: 1 }),
  },
  {
    code: 'CH-ZH',
    name: 'Zurich',
    country: 'CH',
    tile: { col: 14, row: 3 },
    weight: 3,
    capacity: 0.8,
    hazard: H({ Flood: 1.2, Earthquake: 0.7, Fire: 1, Liability: 1, 'Cyber Event': 1.2 }),
  },
  {
    code: 'IT-LOM',
    name: 'Lombardy',
    country: 'IT',
    tile: { col: 13, row: 3 },
    weight: 3,
    capacity: 0.7,
    hazard: H({ Earthquake: 1.4, Flood: 1.5, Fire: 1, Liability: 1 }),
  },
  {
    code: 'ES-MD',
    name: 'Madrid',
    country: 'ES',
    tile: { col: 12, row: 3 },
    weight: 2,
    capacity: 0.6,
    hazard: H({ Wildfire: 1.3, Flood: 1, Fire: 1, Liability: 1 }),
  },
  {
    code: 'ZA-GP',
    name: 'Gauteng',
    country: 'ZA',
    tile: { col: 15, row: 8 },
    weight: 2,
    capacity: 0.5,
    hazard: H({ Fire: 1.1, Liability: 1, Flood: 1.1 }),
  },
  {
    code: 'AE-DXB',
    name: 'Dubai',
    country: 'AE',
    tile: { col: 17, row: 4 },
    weight: 3,
    capacity: 0.7,
    hazard: H({ Fire: 1, Liability: 1, 'Cyber Event': 1.3 }),
  },
  {
    code: 'SG-SG',
    name: 'Singapore',
    country: 'SG',
    tile: { col: 20, row: 6 },
    weight: 4,
    capacity: 0.9,
    hazard: H({ Flood: 1.1, Fire: 1, Liability: 1, 'Cyber Event': 1.4 }),
  },
  {
    code: 'HK-HK',
    name: 'Hong Kong',
    country: 'HK',
    tile: { col: 21, row: 4 },
    weight: 4,
    capacity: 0.9,
    hazard: H({ Windstorm: 1.8, Flood: 1.2, Fire: 1, Liability: 1, 'Cyber Event': 1.2 }),
  },
  {
    code: 'JP-KT',
    name: 'Kantō',
    country: 'JP',
    tile: { col: 23, row: 3 },
    weight: 6,
    capacity: 1.2,
    hazard: H({ Earthquake: 2.7, Windstorm: 1.6, Flood: 1.3, Fire: 1.1, Liability: 1, 'Cyber Event': 1.2 }),
  },
  {
    code: 'JP-KS',
    name: 'Kansai',
    country: 'JP',
    tile: { col: 22, row: 4 },
    weight: 3,
    capacity: 0.8,
    hazard: H({ Earthquake: 2.3, Windstorm: 1.5, Flood: 1.2, Fire: 1, Liability: 1 }),
  },
  {
    code: 'AU-NSW',
    name: 'New South Wales',
    country: 'AU',
    tile: { col: 24, row: 9 },
    weight: 4,
    capacity: 0.9,
    hazard: H({ Wildfire: 2.0, Flood: 1.7, Windstorm: 1.1, Fire: 1, Liability: 1 }),
  },
  {
    code: 'AU-QLD',
    name: 'Queensland',
    country: 'AU',
    tile: { col: 25, row: 8 },
    weight: 3,
    capacity: 0.7,
    hazard: H({ Windstorm: 2.0, Flood: 2.1, Fire: 1, Liability: 1 }),
  },
];

export const ZONE_BY_CODE: ReadonlyMap<string, Zone> = new Map(ZONES.map((z) => [z.code, z]));
export const UNDERWRITERS: readonly string[] = [
  'A. Whitfield',
  'B. Okafor',
  'C. Lindqvist',
  'D. Marchetti',
  'E. Tanaka',
  'F. Abdullah',
  'G. Novak',
  'H. Sørensen',
  'I. Ramirez',
  'J. Hartmann',
  'K. Iyer',
  'L. Dubois',
];
